### ISSUE TITLE
RESTful categories

### ISSUE THREAD

**Issue by timClicks** [ccnz/Ushahidi_Web#57]
_Nathan_W_ 
@timClicks yeh we're hoping to get a URL that can open the map on the chosen category without people having to work out the site
15 seconds ago Favorite Retweet Reply

_Nathan_W_ 
@timClicks k, we're getting specific eqgovtnz questions like "open pharmacies" etc --- keep up the top work too guys...
3 minutes ago 

_Nathan_W_ 
@timClicks Tim is there a way we can grab urls for eq.org.nz that take ppl straight to a specific map category? We're getting enquiries...
1 hour ago

**Comment by ivanjovanovic** [comment]
1. Does it have to be /map/category/category-name or it can be /main#category-name?
2. Just to confirm, we are talking about the home page http://dev.eq.org.nz/main to be extended?

**Comment by timClicks** [comment]
`/main#category-name` seems fine to me

**Comment by mikenz** [comment]
Implemented by pull/59

**Comment by hughbris** [comment]
This is now implemented, but FWIW, it would be far more RESTful to represent a filtered resource using the script path (/category) or a querystring (?category=…) than a fragment identifier (#category). Frag identifiers are meant to represent specific segments of a resource retrieved by HTTP, not a different (filtered) view. Anything requiring Javascript to create your resource representation can't be RESTful.

Sorry I wasn't in here earlier to make the case. It may come back to bite you or not, just sayin' :~).

**Comment by timClicks** [comment]
+1 for using subdirectories or query string if you can spare the energy to implement it.

**Comment by timClicks** [comment]
+1 for using subdirectories or query string if you can spare the energy to implement it.

**Comment by ivanjovanovic** [comment]
I implemented this feature in short amount of time without thinking to much about the essence of all the technical aspects of it.

Anyway, now, from this distance I would argue about the need for RESTful-ness of the categories.

Small disclaimer: I'm not too much (in fact not at all) into the project and all points listed should be taken with consideration of me being potentially ignorant in this given context. If I have one fear in my technical part of life it is about over-engineering things, and thus I share this fear with you :)
1. For me it is not clear what the resource is on the home page and how defining categories as separate resource (in Fieldings REST definition) would fit in overall concept.
2. Considering that you choose to define them as resource and implement /categories/category-name URL scheme, if you just at the end update status of the map, as is currently done, you will end up doing essentially the same as is done now, just URL scheme will be different, but instead of 20 lines of JS you'll end up doing more in PHP which will probably even more, already polluted controller part of this resources MVC.
3. For me most important part is a question what is the goal here. If it was to enable people to have deep linking into the map, then I personally wouldn't go fixing something just for the sake of being RESTful until that is proven to be contributing to the value customer of the product expects from you to deliver. I would not agree that "it might bite you in future" is valid reason, especially with 20 lines solution code.

All the best,
Ivan
